[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pyright]
reportIncompatibleMethodOverride = "warning"

[project]
name = "fiestaEM"
description = "Fast inference of electromagnetic signals with JAX"
version = "0.1.0"
readme = "README.md"
authors = [{ name = "Thibeau Wouters", email = "thibeauwouters@gmail.com"}, { name = "Hauke Koehn", email = "hauke.koehn@uni-potsdam.de"}]
license = "MIT"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["sampling", "inference", "astrophysics", "kilonovae", "gamma-ray bursts", "afterglow", "surrogates"]
requires-python = ">=3.10"
dependencies = [
    "dill",
    "jax",
    "jaxlib",
    "flax",
    "numpy",
    "pandas",
    "jaxtyping",
    "beartype",
    "tqdm",
    "scipy",
    "ml_collections",
    "matplotlib",
    "astropy",
    "sncosmo",
    "flowMC",
    "h5py",
    "corner"
]

[project.optional-dependencies]
grb = ["afterglowpy"]
gpu = ["jax[cuda12]"]
onnx = ["onnx>=1.14", "onnxruntime>=1.16"]

[tool.setuptools]
packages = { find = { where = ["src"] } }

[tool.setuptools.package-data]
"fiesta.surrogates.GRB.afgpy_gaussian_CVAE" = ["**.pkl"]
"fiesta.surrogates.GRB.afgpy_tophat_CVAE" = ["**.pkl"]
"fiesta.surrogates.GRB.pbag_gaussian_CVAE" = ["**.pkl"]
"fiesta.surrogates.GRB.pbag_tophat_CVAE" = ["**.pkl"]
"fiesta.surrogates.KN.Bu2025_MLP" = ["**.pkl"]


[project.urls]
Homepage = "https://github.com/nuclear-multimessenger-astronomy/fiestaEM"