[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pyright]
reportIncompatibleMethodOverride = "warning"

[project]
name = "fiestaEM"
description = "Fast inference of electromagnetic signals with JAX"
version = "0.2.0"
readme = "README.md"
authors = [{ name = "Hauke Koehn", email = "hauke.koehn@uni-potsdam.de"}, { name = "Thibeau Wouters", email = "thibeauwouters@gmail.com"}]
license = "MIT"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["sampling", "inference", "astrophysics", "kilonovae", "gamma-ray bursts", "afterglow", "surrogates"]
requires-python = ">=3.10"
dependencies = [
    "dill",
    "jax>=0.4.14",
    "jaxlib>=0.4.14",
    "flax",
    "numpy",
    "pandas",
    "jaxtyping",
    "beartype",
    "tqdm",
    "scipy",
    "ml_collections",
    "matplotlib",
    "astropy",
    "sncosmo",
    "flowMC",
    "h5py",
    "corner",
    "huggingface_hub>=0.13.0"
]

[project.optional-dependencies]
grb = ["afterglowpy"]
gpu = ["jax[cuda13]"]
docs = [
    "sphinx>=7.0",
    "sphinx-autobuild",
    "sphinx-book-theme>=1.0",
    "sphinx-design>=0.5",
    "sphinx-autodoc-typehints>=2.0",
    "sphinx-copybutton>=0.5",
    "myst-parser>=2.0",
    "dust-extinction",
]

[tool.setuptools]
packages = { find = { where = ["src"] } }

[tool.setuptools.package-data]
"fiesta.inference.tables" = ["csm_table.txt"]

[project.urls]
Homepage = "https://github.com/nuclear-multimessenger-astronomy/fiestaEM"
